# Generated by Django 3.0.3 on 2020-02-25 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VkUsers',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_photo', models.CharField(blank=True, max_length=250, null=True)),
                ('count_friends', models.CharField(blank=True, max_length=5000, null=True)),
                ('django_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(related_name='_vkusers_friends_+', to='core.VkUsers')),
            ],
        ),
    ]
